# Generated by Django 4.1.4 on 2022-12-21 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='processed_installments',
            field=models.IntegerField(default=0),
        ),
    ]
