# Generated by Django 4.1.4 on 2022-12-21 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loan', '0002_loan_processed_installments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loan',
            name='status',
            field=models.IntegerField(choices=[(1, 'Pending'), (2, 'Funded'), (3, 'Completed'), (4, 'Default')], default=1),
        ),
        migrations.AlterField(
            model_name='loanpayments',
            name='status',
            field=models.IntegerField(choices=[(1, 'Scheduled'), (2, 'Paid'), (3, 'Default')], default=1),
        ),
    ]
