# Generated by Django 4.1.4 on 2022-12-22 11:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='borrower',
            name='can_take_loan',
        ),
    ]
